### PR TITLE
CALL FOR CHINESE TRANSLATION

### PR DESCRIPTION
**Pull request by niconiconi**

### CODE REVIEW

**Comment by niconiconi** [comment]
LICENSE SHOULD HAVE A CHINESE VERSION
根据受众，应该添加中文

**Comment by nirui** [comment]
Why you're directly modifying the file? Don't abuse the pull request.

You can translate it into a new file if you wanted to, and then send a pull request to suggest the change.

**Comment by niconiconi** [comment]
Sorry.




不懂法律，不敢乱翻译
I don't familiar with law, cannot translate precisely.

**Comment by niconiconi** [comment]
请有能力的人继续这个pull request
Call for someone to upload the pull request.

**Pull request closed without merging**
