### PR TITLE
Suggesting changing "programmers" to "software engineers"

### PR DESCRIPTION
**Pull request by sureleo**
Suggesting changing "programmers" to "software engineers". 

I have another proposal is to change programmers to IT industry workers.

### CODE REVIEW

**Comment by LBYPatrick** [comment]
I don't see how meaningful this change is.

> 我觉得这个改动没有什么实际意义。

**Comment by bofeiw** [comment]
> Software engineers (SEs), also called software developers, work closely with clients to plan and create software systems. SEs analyze user needs, company requirements, and budget, and they design, develop, and implement a software solution based on those demands. 

> They then give the instructions to computer **programmers**, who write the software codes. 

> Computer programmers receive specifications from software engineers and turn the program design into written instruction codes that the computers will follow. 

Ref https://www.electronicproducts.com/Education/Career/Software_engineer_vs_computer_programmer_what_s_the_difference.aspx

programmer更贴近“程序员”

**Comment by LBYPatrick** [comment]
@bofeiw 嗯，所以我觉得这个改动意义不是太大，况且作者没有指明他们想保护的是996开发者还是所有996的工作者。

根据[996.icu](https://996.icu/#/zh_CN)末尾**相关事件报道**中的内容，这个**programmer**其实也没什么毛病，但如果真要改的话，我倒是觉得这一整段可以改成这样:

> The goal of creating this repository is to address the notorious **996ICU** problem, which refers to a **INHUMANE** work schedule in China that **REQUIRES** workers to work from 9AM to 9PM for six days a week without paying them salaries for the extra hours.

中文翻译过来是这样的:
> (我们)创建这个项目的目的是解决臭名昭著的**996ICU**问题。 “996ICU” 一词出自近日曝光的**非人道**工作安排表--所有在公司内的员工被要求9点上班9点下班，每周6天，且公司不支付额外的加班工资。

你觉得如何？

**Comment by ff4415** [comment]
I like "programmers" more because it takes only one word.

**Comment by LBYPatrick** [comment]
@ff4415 Yep, that's what I initially mean.

**Comment by pjjr123** [comment]
中国程序员
基本都是些农民大学生
人多的跟蟑螂一样
你不做后面几万个人排队
最后的结果 就是996 007
农民的原罪
也是中国问题的原罪
就是农民太多
而且劣性繁殖

**Comment by pjjr123** [comment]
很多人骂我 但是你们想一下
我说的是不是事实
社会资源总量不变
低端人口大量劣性繁殖
最后就是生存环境恶化

你们搞的什么996.icu
最后的结果
就是Github被长城防火墙封杀

**Comment by smallStonela** [comment]
hi，guys，you are so stupid.Farmer count determined socia quality？IQ was kicked. f**k

**Pull request closed without merging**
