### PR TITLE
Remove sensitive information

### PR DESCRIPTION
**Pull request by stupid1t**
Remove sensitive information

### CODE REVIEW

**Comment by nirui** [comment]
~This pull request is attempting to partly undo #24945 (Commit e89caec2b1a3cccba42c0c389d30e2c4d747d1f8 and 88c6eebaae3793d450b1839e5454e832f8ffd116) from the same author (GPG Key seems matched: 4AEE18F83AFDEB23 vs. 4AEE18F83AFDEB23).~

~GitHub has successfully verified the GPG Key.~ 

~See https://github.com/996icu/996.ICU/pull/25513#issuecomment-482781937~

Uh oh, I'm wrong again. GitHub applied the GPG for web commits. So I guess this still is the same original author after all.

**Comment by stupid1t** [comment]
> This pull request is attempting to partly undo #24945 (Commit [e89caec](https://github.com/996icu/996.ICU/commit/e89caec2b1a3cccba42c0c389d30e2c4d747d1f8) and [88c6eeb](https://github.com/996icu/996.ICU/commit/88c6eebaae3793d450b1839e5454e832f8ffd116)) from the same author (GPG Key seems matched: 4AEE18F83AFDEB23 vs. 4AEE18F83AFDEB23).
> 
> GitHub has successfully verified the GPG Key.

What does that mean?

**Comment by nirui** [comment]
> > This pull request is attempting to partly undo #24945 (Commit [e89caec](https://github.com/996icu/996.ICU/commit/e89caec2b1a3cccba42c0c389d30e2c4d747d1f8) and [88c6eeb](https://github.com/996icu/996.ICU/commit/88c6eebaae3793d450b1839e5454e832f8ffd116)) from the same author (GPG Key seems matched: 4AEE18F83AFDEB23 vs. 4AEE18F83AFDEB23).
> > GitHub has successfully verified the GPG Key.
> 
> What does that mean?

Just suggesting that based on my investigation, this pull request have higher credibility since the change is made by the original author rather than some random people trying to remove contents from this repo.

**Comment by stupid1t** [comment]
> > > This pull request is attempting to partly undo #24945 (Commit [e89caec](https://github.com/996icu/996.ICU/commit/e89caec2b1a3cccba42c0c389d30e2c4d747d1f8) and [88c6eeb](https://github.com/996icu/996.ICU/commit/88c6eebaae3793d450b1839e5454e832f8ffd116)) from the same author (GPG Key seems matched: 4AEE18F83AFDEB23 vs. 4AEE18F83AFDEB23).
> > > GitHub has successfully verified the GPG Key.
> > 
> > 
> > What does that mean?
> 
> Just suggesting that based on my investigation, this pull request have higher credibility since the change is made by the original author rather than some random people trying to remove contents from this repo.

Look at the author. I mentioned that before. Now I want to delete the sensitive information of the picture, but the previous fork was deleted by me. I fork again and submit it it.

**Comment by stupid1t** [comment]
> > > This pull request is attempting to partly undo #24945 (Commit [e89caec](https://github.com/996icu/996.ICU/commit/e89caec2b1a3cccba42c0c389d30e2c4d747d1f8) and [88c6eeb](https://github.com/996icu/996.ICU/commit/88c6eebaae3793d450b1839e5454e832f8ffd116)) from the same author (GPG Key seems matched: 4AEE18F83AFDEB23 vs. 4AEE18F83AFDEB23).
> > > GitHub has successfully verified the GPG Key.
> > 
> > 
> > What does that mean?
> 
> Just suggesting that based on my investigation, this pull request have higher credibility since the change is made by the original author rather than some random people trying to remove contents from this repo.

Today, my colleagues in WeChat group found that the picture has regional signs, and then I found that there are few developers in this place

**Comment by nirui** [comment]
> Today, .. <This part has been removed as may contain sensitive information> .. place

I was basically saying that you were the author who added that item in the first place based on GPG Key.

But..... it seems this repository is automatically signing pull requests using GPG Key 4AEE18F83AFDEB23(??). That explains why everybody got the same Key ID.

**Comment by stupid1t** [comment]
> > Today, ..  .. place
> 
> I was basically saying that you were the author who added that item in the first place.
> 
> Also, it seems this repository is automatically signing pull requests using GPG Key 4AEE18F83AFDEB23(??). That explains why everybody got the same Key ID.
ok, can merge?

**Comment by nirui** [comment]
> ok, can merge?

I don't have the permission. ~And to be honest, my investigation is invalid at this point since everybody got the same GPG Key ID.~ See https://github.com/996icu/996.ICU/pull/25513#issuecomment-482779339

Please wait until the admin do the figure. Sorry to bother you.

**Pull request merged**
