### PR TITLE
Misc fix: 9a.m. to 9 a.m.

### PR DESCRIPTION
**Pull request by iF2007**
Misc fix: 
- Change 9a.m. to 9 a.m. Similarly, 9p.m. to 9 p.m.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
这都被你看出来了

**Comment by VanLiuZhi** [comment]
都是些大佬

**Review by ghost — CHANGES_REQUESTED** [review]
建议把 `6 days a week` 改成 `6 days per week`

**Comment by iF2007** [comment]
@lhy0403 Done :)

**Pull request merged**
