### PR TITLE
Create hello,iam the new man to github

### PR DESCRIPTION
**Pull request by oocomeon**

### CODE REVIEW

**Comment by oocomeon** [comment]
ok,cna not be blank

**Comment by oocomeon** [comment]
i dont' know how to work with it

**Comment by 2821840032** [comment]
Please report next door. thank you

**Comment by xianfengting** [comment]
> i dont' know how to work with it

Please do not open meaningless PRs.

**Comment by KyleBing** [comment]
Brave girl,  loves `996`  ?! **NP**

**Pull request closed without merging**
