### PR TITLE
Microsoft and GitHub Workers Support 996.ICU

### PR DESCRIPTION
**Pull request by whtiehack**
https://github.com/msworkers/support.996.ICU

### CODE REVIEW

**Comment by overthrow996schedule** [comment]
把中文版一起改了吧

**Comment by whtiehack** [comment]
logo

**Comment by whtiehack** [comment]
好

**Comment by beanxxy** [comment]
做个加班死亡名单吧。

**Comment by BensonLaur** [comment]
That is great!

**Pull request merged**
