### PR TITLE
感觉好多人在喊这个口号 程序员永不为奴！！！

### PR DESCRIPTION
**Pull request by kwdiwt**
要不就当宣传语用？

### CODE REVIEW

**Comment by kwdiwt** [comment]
会不会被喷屎？

**Comment by JohnsonCaii** [comment]
建议不使用 slave 这个词

**Comment by changeword** [comment]
然后被当狗shi

**Comment by zcyc** [comment]
也许会出现一种情况，某大厂说：我们的工资已经是 2.275 倍了，所有不执行996的员工以后工资除以 2.275。所以大家要保留好劳务合同，合同中写了月工资多少，且这个工资不包含加班费，不是2.275倍的工资，防止变相裁员和恶意降薪。维护合法权益的之前要保护好自己。

There may be a situation where a big factory says: Our salary is already 2.275 times, and all employees who do not perform 996 are divided by 2.275. Therefore, everyone must keep a good labor contract. The contract writes the monthly salary, and this salary does not include overtime pay, not 2.275 times the salary, to prevent disguised layoffs and malicious pay cuts. Protect yourself before you protect your legal rights.
--English version translate by google

**Comment by heliang-whut** [comment]
不要用slave

**Comment by zmlgirl** [comment]
程序员不是猿。

**Comment by 0lovesakura0** [comment]
我们只做该做的，法律规定的，没必要弄啥口号吧

**Pull request closed without merging**
