### PR TITLE
修改大小写

### PR DESCRIPTION
**Pull request by PsChina**
开源工具 "easy-filter" 所在行，修改 "npm" 为 "Npm" 。

### CODE REVIEW

**Review by wchen99998 — COMMENTED** [review]
I do not understand the semantical and syntactical importance of this change. It seems unnecessary.

**Comment by nirui** [comment]
> I do not understand the semantical and syntactical importance of this change. It seems unnecessary.

Your bio says that you are a CS student so I guess you still pretty green on this, but:

```
$ curl https://www.npmjs.com/ 2>/dev/null | grep -o "Npm" | wc -l
1

$ curl https://www.npmjs.com/ 2>/dev/null | grep -o "npm" | wc -l
182
```

And the only occurrence of "Npm" is in 

```
.... "context":{"isNpme":false,"npmExpans ....
```

It don't really counts.

So yeah, programmers are really really picky about case sensitive :)

But now the real question is, why change `npm` to `Npm`?

**Comment by wchen99998** [comment]
> > I do not understand the semantical and syntactical importance of this change. It seems unnecessary.
> 
> Your bio says that you are a CS student so I guess you still pretty green on this, but:
> 
> ```
> $ curl https://www.npmjs.com/ 2>/dev/null | grep -o "Npm" | wc -l
> 1
> 
> $ curl https://www.npmjs.com/ 2>/dev/null | grep -o "npm" | wc -l
> 182
> ```
> And the only occurrence of "Npm" is in
> 
> ```
> .... "context":{"isNpme":false,"npmExpans ....
> ```
> It don't really counts.
> 
> So yeah, programmers are really really picky about case sensitive :)
> 
> But now the real question is, why change `npm` to `Npm`?


Yeah, I am just saying that why change from npm to Npm.
Btw, I definitely understand the importance of case sensitivity.

**Comment by nirui** [comment]
> Yeah, I am just saying that why change from npm to Npm.
> Btw, I definitely understand the importance of case sensitivity.

Actually, importance !== pickiness.

When you messed up something that is important, your code won't compile or run correctly. On the other hand, if you messed up with someone who is picky, you'll be trolled around.

For the record, I'm not saying that you should troll somebody who's trying to change `npm` to `Npm` for the reason currently unknown, but if you do that, I will be fine and probably happy about it. Again, you should NOT do that. Now your turn.

**Comment by wchen99998** [comment]
> > Yeah, I am just saying that why change from npm to Npm.
> > Btw, I definitely understand the importance of case sensitivity.
> 
> Actually, importance !== pickiness.
> 
> When you messed up something that is important, your code won't compile or run correctly. On the other hand, if you messed up with someone who is picky, you'll be trolled around.
> 
> For the record, I'm not saying that you should troll somebody who's trying to change `npm` to `Npm` for the reason currently unknown, but if you do that, I will be fine and probably happy about it. Again, you should NOT do that. Now your turn.

What are you trying to say? Why are you trying to fight me over some nuisance so that you can show off? Just because I am an undergrad does not mean I can not make a valid comment about a pull request. I stick to my opinion that this pull request is unnecessary.

**Comment by loverobaa** [comment]
哥们有才

**Comment by nirui** [comment]
> What are you trying to say? Why are you trying to fight me over some nuisance so that you can show off? Just because I am an undergrad does not mean I can not make a valid comment about a pull request. I stick to my opinion that this pull request is unnecessary.

Well, here is a diagram on what just happened.
Wooosh
Source: https://twitter.com/dyrus/status/848935928261484544

How about we just go back to work and never mention this again?

Oh and just want you to know, no matter what happened between us, I love you all the same.

**Pull request closed without merging**
