### PR TITLE
Update lzh_CN.md

### PR DESCRIPTION
**Pull request by ilovequake3**
调整了文案，冲击力更强了！！！

### CODE REVIEW

**Comment by SmallRedSister** [comment]
https://github.com/SmallRedSister/Mutual-Aid        大家换个地方继续

**Comment by Mqhong** [comment]
怎么issues被关闭了？

**Comment by LaJun** [comment]
来来

**Comment by ShuaiShuaiLee** [comment]
https://hack.chat/?996
应急匿名issue

**Pull request closed without merging**
