### PR TITLE
An invalid submission

### PR DESCRIPTION
**Pull request by BestiOSDev**
撤销本次提交

### CODE REVIEW

**Comment by ShuaiShuaiLee** [comment]
用小号上传

**Comment by ZhaoBingDong** [comment]
我这个提交记录 能被撤销吗 我看到了我的github账户




| |
董招兵
|
|
邮箱：dzb8818082@163.com
|

签名由 网易邮箱大师 定制

在2019年03月31日 14:43，ShuaiShuaiLee 写道：

用小号上传

**Comment by ShuaiShuaiLee** [comment]
不清楚

**Comment by ZhaoBingDong** [comment]
好的 我用小号提交 pull request




| |
董招兵
|
|
邮箱：dzb8818082@163.com
|

签名由 网易邮箱大师 定制

在2019年03月31日 14:47，ShuaiShuaiLee 写道：

不清楚

**Comment by BDZNH** [comment]
建议仓库拥有者应该可以删除，回滚仓库。

**Comment by ZhaoBingDong** [comment]
好的 你那边拒绝我的这次提交




| |
董招兵
|
|
邮箱：dzb8818082@163.com
|

签名由 网易邮箱大师 定制

在2019年03月31日 14:49，BDZNH 写道：

建议仓库拥有者应该可以删除，回滚仓库。

**Comment by 996icu** [comment]
> There is no way you can delete a pull request yourself -- you and the repo owner (and all users with push access to it) can close it, but it will remain in the log. This is part of the philosophy of not denying/hiding what happened during development.

> However, if there are critical reasons for deleting it (this is mainly violation of Github Terms of Service), Github support staff will delete it for you.

> Whether or not they are willing to delete your PR for you is something you can easily ask them, just drop them an email at support@github.com

**Pull request closed without merging**
