### PR TITLE
Caonima.io, a Clojure powered and Shadowsocks-based VPN solution.

### PR DESCRIPTION
**Pull request by danielsz**
Distributed with 996.icu license.

### CODE REVIEW

**Comment by breaking23** [comment]
**聊天室 —— 没有自我审查**

**https://gitter.im/chinapolitics/Gate**

**TOR 浏览器 8.0.8 —— 绕过GFW**

TOR 浏览器

**https://chinagate.gitlab.io**

**Comment by breaking23** [comment]
> 
> 
> Distributed with 996.icu license.

SSL?

**Comment by danielsz** [comment]
I joined the chat but I didn't see you. Yes, the 996.icu license is linked in the repository via SSL (if I understood the question correctly).

**Comment by danielsz** [comment]
Sorry, I don't speak Chinese.

**Pull request merged**
