### PR TITLE
捉虫

### PR DESCRIPTION
**Pull request by bvegetas**
到了2109年说不定996都已经不存在了

### CODE REVIEW

**Comment by longack** [comment]
到那个时候我先死了
就算没有了，也不会改变其违法事实

**Comment by JackHou2005** [comment]
有些事即使消逝也不会改变其原性质

发自我的 iPhone

> 在 2019年8月19日，下午5:19，ShuXuan Yang <notifications@github.com> 写道：
> 
> 到那个时候我先死了
> 就算没有了，也不会改变其违法事实
>

**Comment by bvegetas** [comment]
这个真的是捉虫，2019写成2109了

**Comment by qwas982** [comment]
996的本质是压迫和剥削,
100年后剥削和压迫就不存在了?
100年人类能建成共产主义社会吗

**Comment by Jean1992** [comment]
现在互联网普遍认知就是，程序员的工作性质就应该加班，这是为什么呢？程序员就不是人？

**Comment by huihui1112** [comment]
因为外面嫌程序员赚钱多...


发自网易邮箱大师


在2019年08月26日 09:03，JeanKit<notifications@github.com> 写道：

现在互联网普遍认知就是，程序员的工作性质就应该加班，这是为什么呢？程序员就不是人？

**Comment by Demonrequest4u** [comment]
Does any of this involve ME as a direct personal movement please i would rather just know truth then lies an what I can do to  facilitate wiser

**Comment by onlyGuo** [comment]
> Does any of this involve ME as a direct personal movement please i would rather just know truth then lies an what I can do to facilitate wiser

Easy, update the 996 license to your project！

**Comment by onlyGuo** [comment]
> Does any of this involve ME as a direct personal movement please i would rather just know truth then lies an what I can do to facilitate wiser


Fix it: Chinese capitalists are squeezing their employees'personal time and energy to avoid them becoming potential competitors.

**Comment by onlyGuo** [comment]
> Does any of this involve ME as a direct personal movement please i would rather just know truth then lies an what I can do to facilitate wiser

And our government has acquiesced in these actions of capitalists and provided protection for them.

**Comment by Jean1992** [comment]
> > Does any of this involve ME as a direct personal movement please i would rather just know truth then lies an what I can do to facilitate wiser
> 
> And our government has acquiesced in these actions of capitalists and provided protection for them.

确实是

**Comment by onlyGuo** [comment]
> > > Does any of this involve ME as a direct personal movement please i would rather just know truth then lies an what I can do to facilitate wiser
> > 
> > 
> > And our government has acquiesced in these actions of capitalists and provided protection for them.
> 
> 确实是

毕竟在国内的浏览器中，抗议996 = 违法。

**Pull request merged**
