### PR TITLE
add 深信服 to blacklist

### PR DESCRIPTION
**Pull request by wencan**

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
https://shrinktheweb.snapito.io/v2/webshot/spu-ea68c8-ogi2-3cwn3bmfojjlb56e?size=800x0&screen=1024x768&url=https%3A%2F%2Fwww.v2ex.com%2Ft%2F525495

x
为了防止和谐*（懂的），用 `https://snapito.com/` 截了个图

**Comment by HLdeMJ** [comment]
建议 各位 码们 最好提交截图证据 国内的他们能河蟹。

**Comment by ghost** [comment]
根据这个 PR #24611 改用了 `webarchive`

https://web.archive.org/web/20190330013656/https://www.v2ex.com/t/525495

**Review by ghost — CHANGES_REQUESTED** [review]
再加一个镜像页吧
https://web.archive.org/web/20190330013656/https://www.v2ex.com/t/525495

**Pull request merged**
