### PR TITLE
en_US

### PR DESCRIPTION
**Pull request by shizhediao**
add English version

### CODE REVIEW

**Comment by hyspace** [comment]
Please use en_US.

**Comment by shizhediao** [comment]
> Please use en_US.

fixed

**Review by 996icu — CHANGES_REQUESTED** [review]
Great works! Thank you a lot! 
However, before merged in, it's need to be modified according to current en_US version document.
Please modify it if you still want to update this file.

**Review by getitgetitcenter — COMMENTED** [review]
en_US.md

**Pull request closed without merging**
