### PR TITLE
Add the share link for twitter, facebook, linkedin and etc

### PR DESCRIPTION
**Pull request by exogeny**
future more, we should add more platform share link.

### CODE REVIEW

**Comment by Evezsl** [comment]
我支持965工作模式，欢迎进入965工作模式---->>>http://965.ICU/

**Comment by Miraclemickey** [comment]
cant agree more!

**Comment by maxoes** [comment]
Recommend to add meta properties like for Social Media:

```
<meta property="og:title" content="996.ICU">
<meta property="og:site_name" content="Developers' Lifes Matter">
<meta property="og:url" content="https://996.icu">
<meta property="og:description" content="A "996" work schedule is often adapted for developers in Chinese Companies. It refers to working from 9am to 9pm for 6 days a week. This way we developer will end up in a Intensive Care Unit. ">
<meta property="og:type" content="website">
<meta property="og:image" content="https://github.com/996icu/996.ICU/blob/master/assets/images/logo.png">
```

**Comment by 996icu** [comment]
> Recommend to add meta properties like for Social Media:
> 
> ```
> <meta property="og:title" content="996.ICU">
> <meta property="og:site_name" content="Developers' Lifes Matter">
> <meta property="og:url" content="https://996.icu">
> <meta property="og:description" content="A "996" work schedule is often adapted for developers in Chinese Companies. It refers to working from 9am to 9pm for 6 days a week. This way we developer will end up in a Intensive Care Unit. ">
> <meta property="og:type" content="website">
> <meta property="og:image" content="https://github.com/996icu/996.ICU/blob/master/assets/images/logo.png">
> ```

Open graph tag added

**Pull request closed without merging**
