### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by wanglikun7342**

### CODE REVIEW

**Comment by izvkh2** [comment]
支持996.ICU
欢迎大家加入996反抗联盟电报群
https://t.me/anti996

**Comment by Evezsl** [comment]
我支持965工作模式，欢迎进入965工作模式---->>>http://965.ICU/

**Comment by xiezhaokun** [comment]
哈哈哈

**Comment by xiezhaokun** [comment]
哈哈哈

**Comment by piedro** [comment]
Work 996, Sick in ICU: https://qr.ae/TW11PB  
The http://996.icu  is an open source software license that Prohibited companies to use for business in violation of labor laws. Marx may not have thought that the 21st century has reached the era of cyber labor

996.ICU telegram group
https://t.me/joinchat/E2YNXE8WpJWvceLzozEkUQ

**Comment by 996icu** [comment]
996.LIST shows the result of the voting page.

**Pull request closed without merging**
