### PR TITLE
Remove Unnecessary Stuff From README.md

### PR DESCRIPTION
**Pull request by Fluffy728**
Yeah bro you should have not done that

Approve me!

### CODE REVIEW

**Comment by ui0ppk** [comment]
why?? do you not understand why this exists?

**Comment by dongYkuan** [comment]
来信已收到，谢谢！

**Comment by peterzang** [comment]
已收到。谢谢

**Comment by winghou** [comment]
邮件已经收到！更多精彩请看以下内容
企业微信自动化添加客户软件 企业微信群 qywxq.com

**Pull request closed without merging**
