### PR TITLE
96hour-one week

### PR DESCRIPTION
**Pull request by gsxuan**
call 120 for me

### CODE REVIEW

**Comment by yeningyuan08** [comment]
I am a Chinese middle school student.I can help you.

**Comment by chinyichun** [comment]
I just did call 120 for you, and also 911.

**Comment by itfootman** [comment]
咱们这个有群吗



At 2020-10-24 20:55:47, "chinyichun" <notifications@github.com> wrote:

I just did call 120 for you, and also 911.

**Comment by chinyichun** [comment]
> 咱们这个有群吗 

@itfootman 什么群？微信群？QQ群？在微信QQ上设996.ICU群是想找死？

**Pull request closed without merging**
